# vim: set ts=2 et:

matrix:
  include:

    # Linux + Postgresql 9.5
    - os: linux
      dist: trusty
      sudo: required
      language: generic
      env:
      addons:
        apt:
          packages:
            - cmake
            - postgresql-9.5
      before_install:
        - make test

